title: I slipped on a crab. Who put that crab there?
description: Linux Sandbox Script and what else ?
author: Tug
remote_theme: just-the-docs/just-the-docs

# Enable or disable the site search
search_enabled: true

# Set the color scheme to dark
color_scheme: dark

# URL of the logo image
logo: "/assets/images/logo.jpg"