title: Mon Blog
description: Bienvenue sur mon blog.
author: Baptiste
remote_theme: just-the-docs/just-the-docs

# Enable or disable the site search
search_enabled: true

# Set the color scheme to dark
color_scheme: dark

# URL of the logo image
logo: "/assets/images/logo.jpg"
